# Generated by Django 2.2.4 on 2021-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favbooksapp', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='hello its me'),
            preserve_default=False,
        ),
    ]
