# Generated by Django 2.2.4 on 2021-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshowsapp', '0002_auto_20210524_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
